### ISSUE TITLE
Expose max_retries option

### ISSUE THREAD

**Issue by johnbelamaric** [infobloxopen/infoblox-client#104]
The Requests module supports a "max_retries" option:

http://docs.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter

We should expose that for users of the connector. Note that it can be an integer or a Retry object, so we should support that too.

See also

https://community.infoblox.com/t5/API-Integration/Infoblox-python-API-help/m-p/5725#M482

**Comment by bondar-pavel** [comment]
John, thanks for reporting it. 
I'll investigate deeper with it today.

What is the priority for this issue?

**Comment by bondar-pavel** [comment]
Actually this one looks easy to do, so probably I'll prepare pull request for it today.

**Comment by johnbelamaric** [comment]
Low - unless we see the request timeout not fixing the issue on the community forum.

I have used the retry before in the Heat code (which doesn't use this lib yet). For me it was an issue because I was running everything on Fusion on my laptop so there were some timeouts. The retry made it all work smoothly.

**Comment by bondar-pavel** [comment]
I have tested it locally and it worked well.

To emulate connection timeout I turned off vpn, so 10.40.240.113 become unreachable.
After it execute 'objects.Network.search_all(conn)' to make sure first requests can not reach Grid. After 5-10 seconds I bring vpn up and  results were successfully returned.

Here is console log with max debug:

> In [15]: objects.Network.search_all(conn)
INFO:infoblox_client.connector:Sending get request to https://10.40.240.113/wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5 with parameters {'headers': {'Content-type': 'application/json'}, 'timeout': 10}
/home/pavel/.venv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
DEBUG:requests.packages.urllib3.util.retry:Incremented Retry for (url='/wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5'): Retry(total=2, connect=None, read=None, redirect=None)
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='10.40.240.113', port=443): Read timed out. (read timeout=10)",)': /wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): 10.40.240.113
DEBUG:requests.packages.urllib3.util.retry:Incremented Retry for (url='/wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5'): Retry(total=1, connect=None, read=None, redirect=None)
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a8ae65310>, 'Connection to 10.40.240.113 timed out. (connect timeout=10)')': /wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): 10.40.240.113
DEBUG:requests.packages.urllib3.util.retry:Incremented Retry for (url='/wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5'): Retry(total=0, connect=None, read=None, redirect=None)
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a8ae65510>, 'Connection to 10.40.240.113 timed out. (connect timeout=10)')': /wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): 10.40.240.113
/home/pavel/.venv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
DEBUG:requests.packages.urllib3.connectionpool:"GET /wapi/v1.4/network?_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs&_max_results=5 HTTP/1.1" 200 None
Out[15]:
[NetworkV4: members="[AnyMember: ipv4addr="10.40.240.113", name="stan_member.ft-ac.com", _struct="dhcpmember"]", _ref="network/ZG5zLm5ldHdvcmskMTAuNDAuMjQwLjAvMjQvMA:10.40.240.0/24/test", network="10.40.240.0/24", network_view="test", options="[DhcpOption: vendor_class="DHCP", num="51", name="dhcp-lease-time", value="43200", use_option="False", DhcpOption: vendor_class="DHCP", num="6", name="domain-name-servers", value="10.0.2.35", use_option="True", DhcpOption: vendor_class="DHCP", num="3", name="routers", value="10.40.240.1", use_option="True"]",
 NetworkV4: members="[AnyMember: ipv4addr="10.40.240.113", name="stan_member.ft-ac.com", _struct="dhcpmember"]", _ref="network/ZG5zLm5ldHdvcmskMTAuNDAuMTYuMC8yNC8w:10.40.16.0/24/test", network="10.40.16.0/24", network_view="test", options="[DhcpOption: vendor_class="DHCP", num="51", name="dhcp-lease-time", value="43200", use_option="False", DhcpOption: vendor_class="DHCP", num="6", name="domain-name-servers", value="10.0.2.35", use_option="True", DhcpOption: vendor_class="DHCP", num="3", name="routers", value="10.40.16.1", use_option="True"]"]
