### ISSUE TITLE
Use http instead of https in the connector

### ISSUE THREAD

**Issue by thermobob** [infobloxopen/infoblox-client#109]
Hi, Is this possible to create a method which will change from the default https connection to a http one?
I know that it is a security risk to run over plain http but it would be a nice feature to be able to change it and run over http. You can leave the default as https and introduce the possibility to change to http.
Best regards,
Bogdan

**Comment by johnbelamaric** [comment]
I don't think the DDI appliances support HTTP, only HTTPS.

**Comment by thermobob** [comment]
I see, thank you for your answer.
/Bogdan
