### ISSUE TITLE
'ipv4addr' field needed for dhcpmember in creating network for old NIOS

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#111]
In older NIOS like 6.11.7 (WAPI version 1.6), 'dhcpmember' requires 'ipv4addr' field.

Here is how this is implemented in older IPAM driver.

create_network in object manager:

        members_struct = []
        for member in members:
            members_struct.append({'ipv4addr': member.ip,
                                   '_struct': 'dhcpmember'})
        network_data['members'] = members_struct

"ipv4addr" field of "member" list is mandatory in 6.12.x build, whereas it is optional in 7.3 build.

We will need to support this in object manager.

**Comment by bondar-pavel** [comment]
Current infoblox-client design expects members to be created as AnyMember class and passed to create_network. So members are prepared in this case outside infoblox-client.
AnyMember already has all need fields:
```
 class AnyMember(SubObjects):
    _fields = ['_struct', 'name', 'ipv4addr', 'ipv6addr']
```

I'll update create_network docstring to clearly express expected input.

**Comment by bondar-pavel** [comment]
mentioned docstring update https://github.com/infobloxopen/infoblox-client/pull/115

**Comment by bondar-pavel** [comment]
Issue is fixed on networking-infoblox side:
https://review.openstack.org/#/c/297185/
