### ISSUE TITLE
Search for partial match is undocumented

### ISSUE THREAD

**Issue by jobec** [infobloxopen/infoblox-client#112]
It's unclear how to search for partial matches.

After some struggling I found out you can do a partial match with the low level API like so:

    conn = connector.Connector(opts)
    nw = conn.get_object('network', {'network~': '10.10.'})

But how to 'seach' this way with the high level seach function? I couldn't figure out a way to do so.

**Comment by bondar-pavel** [comment]
@jobec Hi, currently partial match search is not supported for high level API. And thanks for bringing that up. I need to think a bit about how to organically add partial match search for high level API.

Will keep you posted about the progress.

**Comment by jobec** [comment]
@bondar-pavel  this partial matching is also sort of undocumented for the low level API.
It's logical that is works, but it took me a while to make the link between the python client and the fact that it send the paramters as-is instead of treating it like a field.

**Comment by bondar-pavel** [comment]
Adding examples of search by regular expression into README.rst #124

**Comment by bondar-pavel** [comment]
Closing the issue, since examples were added into README.rst
