### ISSUE TITLE
Support ipv4address/ipv6address

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#114]
Using ipv4address/ipv6address objects is a convenient way to check if any object that related to ip address exists.

In the old driver, we used this call for get_all_associated_objects.
This is a better way to search if an IP address exists or not regardless IP type such as host record vs fixed address. Also, this gives all the dependent objects.

Currently, I am using this call to search for a dhcp port IP when dns view does not exist in case DHCP/DNS supports are turned off.

```
        assoc_with_ip = {
            'network_view': netview,
            'ip_address': ip_address
        }
        obj_type = ('ipv4address'if utils.get_ip_version(ip_address) == 4
                    else 'ipv6address')
        ib_address = connector.get_object(obj_type,
                                          assoc_with_ip,
                                          return_fields=['objects'])
```

It would be nice to build the class for this.

**Comment by sarya-infoblox** [comment]
Hi @hosunghwang  Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.
