### ISSUE TITLE
Trying to search using regular expresssions

### ISSUE THREAD

**Issue by rcorrieri** [infobloxopen/infoblox-client#116]
Hello Everyone.!
I am trying to execute a search of any of the supported objects using regular expressions.
Because some internal audit we need to address at my Company from time to time, it would be very useful for us to be able to query the Infoblox looking for records matching a regular expression.
So I may get more than one individual result.
As far as I can see, the search() and search_all() methods only support to provide the exact value for the field we are looking for.
May be I am wrong.
If this is the case, I will really appreciate a simple example retrieving a set of HostRecord objects using a regular expression.
Thanks.

Ricardo Corrieri

**Comment by bondar-pavel** [comment]
Hi @rcorrieri!
This is similar to #112. There is no high level API for that, but for low-level case you can use next approach:

```
conn = connector.Connector(opts)
nw = conn.get_object('network', {'network~': '10.10.'})
```

So for host record case it will look like:
```
conn = connector.Connector(opts)
hr = conn.get_object('record:host', {'ipv4addr~': '10.10.'})
```
This should find all host records in 10.10.0.0/16 network.
It is not the most effective way to search host records that belongs to network, used here just as example.

Check out wapi documentation to find out which fields can be searched by reqular expressions: https://your_nios_ip/wapidoc/objects/record.host.html?highlight=record%3Ahost#record:host

**Comment by rcorrieri** [comment]
Hello Pavel, and thanks for your reply...!

Yes, while digging into the pending issues to be fixed in your repo, I
found your reply to this same question.

And it's ok, I am already re-coding my module to use it.

Thanks so much again...!

Ricardo Corrieri

**Comment by rcorrieri** [comment]
One more question.

How do you manage to restrict the amount of objects to be retrieved...?

Some field to add to my query like:

max_results = 3000

I am looking for all PTR records where their 'name' field matches a
specific pattern.

And Infoblox is telling me I am asking for more than 1000 records, so it
returns nothing.

Thanks.

**Comment by rcorrieri** [comment]
Nevermind, I've been too lazy, sorry about that.

This parameter is defined in the get_object() method.

Thanks.

Ricardo Corrieri

**Comment by bondar-pavel** [comment]
Looks like resolved, so closing this issue.

**Comment by rcorrieri** [comment]
Yes, thanks so much.!
