### ISSUE TITLE
Question about binary distribution build

### ISSUE THREAD

**Issue by rcorrieri** [infobloxopen/infoblox-client#122]
After to replace my former Infoblox API by this current one, I need to take care of the installation of python-dev and gcc compiler in the target hosts. I did not need this steps before.
I've been checking your source code, but it seems to be pure Python.
So I am not sure why I do need to include these packages in my original distribution now, when building my tarball.
Any pointers will be appreciated.
Thanks.

**Comment by bondar-pavel** [comment]
@rcorrieri Hi!
infoblox-client itself is pure python package.
Looks like one of it's dependencies causes this effect:
https://github.com/infobloxopen/infoblox-client/blob/master/requirements.txt

And my guess is that 'requests' is the one that require compiling binaries.
https://pypi.python.org/pypi/requests#downloads

**Comment by rcorrieri** [comment]
Great, thanks so much for the fast response.!

I will keep checking.

You can close this issue, then.

Best,

Ricardo Corrieri
