### ISSUE TITLE
create_required_ea_definitions does not throw exception

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#125]
QA created a test case where an EA def creation would fail when testing OPENSTACK-839.

See the trace from OPENSTACK-839

> EA def creation failed but does not throw any error in create_required_ea_definitions
> 2016-06-05 23:46:37.557 DEBUG infoblox_client.connector [-] Sending get request to https://10.39.12.170/wapi/v2.3/extensibleattributedef?_return_fields=comment%2Cdefault_value%2Cflags%2Clist_values%2Cmax%2Cmin%2Cname%2Cnamespace%2Ctype%2Callowed_object_types with parameters {'headers': {'Content-type': 'application/json'}, 'timeout': 120} from (pid=9535) _log_request /usr/local/lib/python2.7/dist-packages/infoblox_client/connector.py:202
> 2016-06-05 23:46:37.695 DEBUG infoblox_client.connector [-] Sending post request to https://10.39.12.170/wapi/v2.3/extensibleattributedef?_return_fields=comment%2Cdefault_value%2Cflags%2Clist_values%2Cmax%2Cmin%2Cname%2Cnamespace%2Ctype%2Callowed_object_types with parameters {'headers': {'Content-type': 'application/json'}, 'data': '{"comment": "Cloud Participation", "type": "STRING", "flags": "CV", "name": "Cloud Adapter ID"}', 'timeout': 120} from (pid=9535) _log_request /usr/local/lib/python2.7/dist-packages/infoblox_client/connector.py:202
> 2016-06-05 23:46:37.722 ERROR infoblox_client.object_manager [-] Unable to create Extensible Attribute Definition {'comment': 'Cloud Participation', 'flags': 'CV', 'type': 'STRING', 'name': 'Cloud Adapter ID'}
> The following EA Definitions have been created: '['Cloud Adapter ID']'

Since an exception is not thrown, no way to detect an error. 
Also missing_ea_defs still returns with the EA that has been failed to create.

**Comment by bondar-pavel** [comment]
Adding optional parameter for create_ea_definition and create_required_ea_definitions  to reraise error in case of failure.
