### ISSUE TITLE
SRV records

### ISSUE THREAD

**Issue by akuzminsky** [infobloxopen/infoblox-client#137]
Can I create/modify/delete an SRV record?

**Comment by yuewko** [comment]
infoblox-client currently does not support SRV record. But, that's only because we haven't yet had a need for it. Adding it should be straightforward. Do you have any specific use case in mind?

BTW, code contribution is always welcome ;-)

**Comment by akuzminsky** [comment]
We need it to bootstap an etcd cluster(https://coreos.com/etcd/docs/latest/clustering.html#dns-discovery) . if i implement it i'll send a PR. :)

**Comment by yuewko** [comment]
Interesting - we are looking at similar use cases too.
If you need anything from us, please do not hesitate to ping us.
