### ISSUE TITLE
Include the ability to pass an "exclude" param on to infoblox for get_next_available_ip

### ISSUE THREAD

**Issue by Zamboughnuts** [infobloxopen/infoblox-client#149]
In our organization, we reserve the first 10 IP addresses in any large subnet. Unfortunately, the "func:getnextavailableip" command doesn't support this; it expects either CIDR notation, or a specified DHCP range, and it has to match. 

I know there's a "long form" version of the POST request that is able to have an "excluded addresses" option. I've successfully used this in another python-based infoblox connector in the past. 

`
{
 "name":"wapi.test.org", 
     "ipv4addrs":[
            ipv4addr" : {
                "_function" : 'next_available_ip' ,
                "_object_field" : 'value' ,
                "_object" : '10.10.10.0/24' ,
                "_parameters" : {
                   "num" : 1,
                   "exclude" : [ '45.0.1.1' , '45.0.1.2' ],
                }
            }
        ]
    }
`

Is there any way to have that functionality added to this connector? I'm aware that it would involve quite a lot of tweaking of the "objects" class to work correctly.

**Comment by yuewko** [comment]
As a workaround, you could use,
```
    def create_fixed_address_from_range(self, network_view, mac, first_ip,
                                        last_ip, extattrs):
```
to specify the range of IP from which to allocate the IP.
Would that work?

**Comment by sarya-infoblox** [comment]
Hi @Zamboughnuts was your issue resolved?

**Comment by Zamboughnuts** [comment]
I haven't used this functionality in years, this issue can be closed.

**Comment by sarya-infoblox** [comment]
Closing the issue.
