### ISSUE TITLE
Search DHCP Network range via IP in that range

### ISSUE THREAD

**Issue by hawthorn** [infobloxopen/infoblox-client#169]
In perl, we are able to search a range for "Contains" - this returns a Network object with all attributes.
What (if any object) can I use that is similar to this functionality?

```perl
my @retrieved_objs = $session->get(
        object => "Infoblox::DHCP::Network",
        contains_address => $FindIP  
);
```

**Comment by hawthorn** [comment]
i = infoblox.Infoblox('gird', 'user','pw','1.6','internal','default')
net_addr = i.get_network_by_ip(FINDIP)
network = i.get_network(net_addr)
net_attr = i.get_network_extattrs(network)

I guess I just needed to type up the issue ....

**Comment by achernevskii** [comment]
You can get `IPAddress` directly and then access the `network` property, to get the network address. 

For example, on my WAPI instance the following code:
```python
ipaddr = objects.IPAddress.search(conn, ip_address='192.168.1.15')
print(ipaddr.network)
```
WIll print:
```
192.168.1.0/24
```

Would that work for you?

**Comment by sarya-infoblox** [comment]
Hi @hawthorn can you confirm if the solution provided above resolves your issue?

**Comment by hawthorn** [comment]
This resolved the issue

**Comment by sarya-infoblox** [comment]
Closing the issue.
