### ISSUE TITLE
Issue querying PTR records

### ISSUE THREAD

**Issue by ku0100** [infobloxopen/infoblox-client#172]
I am having difficulty being able to successfully query ptr records that exist. I have a test lab appliance that I am messing with. I have created a zone called test.com as well as another zone, 1.1.in-addr.arpa for reverse-mapping. I created two host records in the test.com zone:
 
1. test1.test.com - 1.1.1.1
2. test2.test.com - 1.1.1.2
 
When I go to the 1.1.in-addr.arpa zone on the Infoblox GUI, I see the reverse ptr records for both of those records but when I try the following calls in my explorer, none show me either of those records:
 
https://lab-infoblox1/wapi/v2.2.2/record:ptr?ipv4addr=1.1.1.1.in-addr.arpa
https://lab-infoblox1/wapi/v2.3.1/record:ptr?ipv4addr=1.1.1.1
https://lab-infoblox1/wapi/v2.2.2/record:ptr?ipv4addr=1.1.1.2.in-addr.arpa
https://lab-infoblox1/wapi/v2.3.1/record:ptr?ipv4addr=1.1.1.2
https://lab-infoblox1/wapi/v2.3.1/record:ptr?ip=1.1.1.1.in-addr.arpa
https://lab-infoblox1/wapi/v2.3.1/record:ptr?ip=1.1.1.1
https://lab-infoblox1/wapi/v2.2.2/record:ptr?ip=1.1.1.2.in-addr.arpa
https://lab-infoblox1/wapi/v2.3.1/record:ptr?ip=1.1.1.2
 
Is there something I am missing? This is for an app I'm writing in Python but I dont think that code is necessary. Is my syntax/formatting for these calls somehow wrong?

I did some further investigation and it seems at this point that the creation of a Host record doesn't actually create an A record or PTR record that can be manipulated (queried, altered, etc) at all. Is this accurate? When I look up the reverse DNS of the above entry, I see host records, not PTR records. Can anyone confirm? If this is the case, it looks like it makes sense to just create separate A records and PTR records instead of host records
 
Thank you

**Comment by sarya-infoblox** [comment]
Hi @ku0100 can you confirm if the solution provided above resolves your issue?

**Comment by sarya-infoblox** [comment]
Hi @ku0100 Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.
