### ISSUE TITLE
Updating CNAME record

### ISSUE THREAD

**Issue by pjewiec** [infobloxopen/infoblox-client#180]
Hi,

I'm trying to update a canonical name in a CNAME record. Unfortunately I can't find any information about that. I tried using
`ar = objects.CNAMERecord.search(conn, name=raddr)`
`old_canonical = ar.canonical`
`new_canonical = unicode(rhost, "utf-8")`
`ar.canonical.replace(old_canonical, new_canonical)`
`ar.update()`

but canonical is not being updated. What am I doing wrong?

**Comment by pjewiec-priv** [comment]
NVM, i just did it with:
`ar.canonical = new_canonical`
`ar.update()`

**Comment by saiprasannasastry** [comment]
closing since you found the fix
