### ISSUE TITLE
HostRecord.create with "update_if_exists=True" throws "record already exists"

### ISSUE THREAD

**Issue by bandit145** [infobloxopen/infoblox-client#181]
I'm hitting an issue while trying to update an already created host record in infoblox (wapi version 1.7.1),
if I try to update the IP address of the host record I get "record already exists". If I attempt to update other attributes that works fine.

I noticed this issue https://github.com/infobloxopen/infoblox-client/issues/68 , which seems similar except that it's for merging ip addresses.

Thanks.

This was tested on CentOS 7.4 with Python 3.4 with the newest version of infoblox-client.

Script to recreate:

https://gist.github.com/bandit145/c823a7c860ce97d165308481facaaf68

**Comment by rajathav28** [comment]
Hi, I can see that you are trying to create a host record where you are trying to pass the argument "update_if_exists" but the function you are trying to implement is Update an IP. 
But the Create method is only used for an record creation and not for update and hence you get the error "record already exists"

Instead if you would like to update the IP of a record you can specifically use the update function. 

You can refer below for an example code which does an IP update:

```
  #make sure you have a view and zone created and connected to NIOS.
  host_record=objects.HostRecord.create(conn, ip=objects.IP.create('192.169.1.25'), view="your_view", 
                        name="test.your_zone.com", configure_for_dns=True, ttl=None, comment=None,
                        extattrs=None)
  #here we update the objects variable and call the update function
  host_record.ip=objects.IP.create('192.169.1.26')
  host_record.update()
```

**Comment by bandit145** [comment]
@rajathav28 Thanks for the response! This is a non-issue for me now that there are the official Infoblox Ansible modules but I appreciate the clarification.
