### ISSUE TITLE
No Comments on A and CNAME Records

### ISSUE THREAD

**Issue by markeganfuller** [infobloxopen/infoblox-client#194]
Comments can neither be queried nor set on A or CNAME records.

* If a A or CNAME is created with a comment, the record is created but the comment is not set.
* If a record with a comment set is queried, there is no way to access this value.

e.g.

```python
# Results in A record without comment
objects.ARecord.create(
    connector=conn,
    ip='127.1.1.1',
    name="an.example.com",
    comment="testing things",
    view="Internal"
)
```
```python
# A record with Comment set via web interface
example = objects.ARecord.search(connector=conn, ipv4addr="127.1.1.1")
example.comment  # Attribute Error
example.__dict__

{'connector': <infoblox_client.connector.Connector at 0x7fe494811fd0>,
 'ipv4addr': '127.1.1.1',
 'name': 'an.example.com',
 'view': 'Internal',
 'extattrs': None,
 '_ref': 'record:a/ZG5zLmJpbmRfYSQuMS51ay5hYy5xbXVsLmhwYyx0ZXN0LDEyNy4xLjEuMQ:an.example.com/Internal'
}
```

**Comment by markeganfuller** [comment]
That doesn't seem to work:
```python
example = objects.ARecord.search(
    connector=conn,
    ipv4addr="127.0.0.1",
    return_fields=['comment', 'ipv4addr', 'name', 'view'],
    view="Internal"
)

example.to_dict()

{'ipv4addr': '127.0.0.1',
 'name': 'an.example.com',
 'view': 'Internal'
}

example.__dict__

{'connector': <infoblox_client.connector.Connector at 0x7fe92dd25ba8>,
 'ipv4addr': '127.0.0.1',
 'name': 'an.example.com',
 'view': 'Internal',
 'extattrs': None,
 '_ref': 'record:a/ZG5zLmJpbmRfYSQuMi51ay5hYy5xbXVsLmhwYyxleHR0ZXN0b25seSwxMjcuMC4wLjE:an.example.com/Internal'
}
```

**Comment by markeganfuller** [comment]
The low level API can be used as a workaround to this:

```python
record = conn.get_object(
    'record:a',
    {
        'view':  'External',
        'name': 'an.example.com',
    }
)

conn.update_object(
    record[0]['_ref'],
    {
        'comment': 'A comment',
    }
)
```

**Comment by saiprasannasastry** [comment]
Hi tried this out, and it is working fine, while doing search when i print example.comment , it returns comment.
creation also works fine

**Comment by saiprasannasastry** [comment]
Hi, you can search like this
kwargs = {
        'return_fields': [
            'ipv4addr',
            'comment',
        ]
    }
example = objects.ARecord.search_all(connector=conn, **kwargs)


returns something like this [ARecord: comment="testing things", _ref="record:a/ZG5zLmJpbmRfYSQuX2RlZmF1bHQuY29tLmV4YW1wbGUsYW4sMTAuMC4wLjQ:an.example.com/default", ipv4addr="10.0.0.4", ARecord: comment="sfdaefgegf", _ref="record:a/ZG5zLmJpbmRfYSQuX2RlZmF1bHQuY29tLmV4YW1wbGUsc2FpLDEwLjAuMC41:sai.example.com/default", ipv4addr="10.0.0.5", ARecord: comment="dgsd", _ref="record:a/ZG5zLmJpbmRfYSQuX2RlZmF1bHQuY29tLmV4YW1wbGUsZSwxMC4wLjAuMw:e.example.com/default", ipv4addr="10.0.0.3"]

**Comment by saiprasannasastry** [comment]
comment was not specified in _fields and hence you were not able to add a comment
