### ISSUE TITLE
Creating A Record with existing IP Data conflicts or overwrites existing IP

### ISSUE THREAD

**Issue by limitedreality** [infobloxopen/infoblox-client#204]
CentOS 7.4.1708
infoblox-client 0.4.20
Python 3.6.5

So I've found that if I try to create an A record for an IP not already used in an existing zone it creates fine.  Example test below using test.example.com:
>>> server = 'test'
>>> ip = '1.1.2.1'
>>> hostname = server + '.example.com'
>>> opts = {'host': infoblox_IP, 'username': infoblox_username, 'password': infoblox_password}
>>> conn = connector.Connector(opts)
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
>>> a_record = objects.ARecord.create(conn, name=hostname, ip=ip)
DEBUG:infoblox_client.connector:Sending get request to https://IP-REMOVED/wapi/v2.1/record%3Aa?ipv4addr=1.1.2.1 with parameters {'timeout': 10, 'headers': {'Content-type': 'application/json'}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): IP-REMOVED
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://IP-REMOVED:443 "GET /wapi/v2.1/record%3Aa?ipv4addr=1.1.2.1 HTTP/1.1" 200 None
DEBUG:infoblox_client.connector:Sending get request to https://IP-REMOVED/wapi/v2.1/record%3Aa?ipv4addr=1.1.2.1&_proxy_search=GM with parameters {'timeout': 10, 'headers': {'Content-type': 'application/json'}}
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://IP-REMOVED:443 "GET /wapi/v2.1/record%3Aa?ipv4addr=1.1.2.1&_proxy_search=GM HTTP/1.1" 200 None
DEBUG:infoblox_client.connector:Sending post request to https://IP-REMOVED/wapi/v2.1/record%3Aa with parameters {'timeout': 10, 'headers': {'Content-type': 'application/json'}, 'data': '{"ipv4addr": "1.1.2.1", "name": "test.example.com"}'}
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://IP-REMOVED:443 "POST /wapi/v2.1/record%3Aa HTTP/1.1" 201 None
INFO:infoblox_client.objects:Infoblox record:a was created: ARecord: ipv4addr="1.1.2.1", name="test.example.com"

But if I were to try to assign the same IP to a different A record (test2.example.com) it fails as though that were a conflict?
>>> opts = {'host': infoblox_IP, 'username': infoblox_username, 'password': infoblox_password}
>>> conn = connector.Connector(opts)
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
>>> a_record = objects.ARecord.create(conn, name=hostname, ip=ip)
DEBUG:infoblox_client.connector:Sending get request to https://IP-REMOVED/wapi/v2.1/record%3Aa?ipv4addr=1.1.2.1 with parameters {'timeout': 10, 'headers': {'Content-type': 'application/json'}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): IP-REMOVED
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://IP-REMOVED:443 "GET /wapi/v2.1/record%3Aa?ipv4addr=1.1.2.1 HTTP/1.1" 200 None
INFO:infoblox_client.objects:Infoblox record:a already exists: ARecord: ipv4addr="1.1.2.1", name="test2.example.com", _ref="record:a/ZG5zLmJpbmRfYSQuX2RlZmF1bHQuaG9zdC5kYXRhYmFuayx0ZXN0LDEuMS4yLjE:test.example.com/default"

Even worse, if you add the parameter to  update_if_exists=True it replaces the test.example.com A record with test2.example.com.

I would expect to be able to create multiple A records pointed to the same IP through the client and that update would update test2.example.com to the IP I'm providing.  Please let me know if I'm misunderstanding something or if there's another way to achieve what I'm trying to do.

Thanks!

**Comment by saiprasannasastry** [comment]
Hi, please use it like this to create multiple records
This creates multiple records for same IP
`
objects.ARecord.create(
    connector=conn,
    ip='10.0.0.2',
    name="a5.example.com",
    view="default",
    check_if_exists=False
)
`
