### ISSUE TITLE
How to create network container?

### ISSUE THREAD

**Issue by cmacnevin** [infobloxopen/infoblox-client#208]
Hi,

'get' network object works fine using:
conn.get_object('network', {'network': nw})
and 'get' network container works fine using:
conn.get_object('networkcontainer', {'network': nw})

creating networks works fine using:
view='Internal', network_view='default', comment=comment)
BUT, the following results in an AttributeError:
objects.NetworkContainer.create(conn, cidr=nw, view='Internal', network_view='default', comment=comment)

So, is there a method for doing this? Digging around hasn't turned anything up so far.

**Comment by Precission** [comment]
There is no object for NetworkContainer. You can use the create_object for every object in Infoblox.
```conn.create_object('networkcontainer', {'network': nw})```
