### ISSUE TITLE
0.4.22 is not on PyPI

### ISSUE THREAD

**Issue by JonasKs** [infobloxopen/infoblox-client#217]
Version has been bumped to 0.4.22, but PyPI is still on 0.4.21.

**Comment by JonasKs** [comment]
@saiprasannasastry , tagging you since you did the bump.

**Comment by saiprasannasastry** [comment]
Thankyou for raising an issue ,will try to resolve it ASAP. I am asking for pypi access,as soon as i get it i will do .

**Comment by saiprasannasastry** [comment]
it has been updated on pypi as well
