### ISSUE TITLE
Update does not work for host record

### ISSUE THREAD

**Issue by rainierpineda2** [infobloxopen/infoblox-client#220]
I tried an update on a host record but it does not work
```
>>> new
HostRecordV4: _ref="record:host/ZG5zLmhvc3QkLjMuY29tLm1yc2htYy50ZXN0MTEx:test111.example.com/Internal", ipv4addr="192.168.244.2", ipv4addrs="[IPv4: configure_for_dhcp="False", ip="192.168.244.2", _ref="record:host_ipv4addr/ZG5zLmhvc3RfYWRkcmVzcyQuMy5jb20ubXJzaG1jLnRlc3QxMTEuMTkyLjE2OC4yNDQuMi4:192.168.244.2/test111.example.com/Internal", ipv4addr="192.168.244.2", host="test111.example.com"]"

>>> new.ipv4addr = '192.168.244.3'
>>> new.update()
HostRecordV4: _ref="record:host/ZG5zLmhvc3QkLjMuY29tLm1yc2htYy50ZXN0MTEx:test111.example.com/Internal", ipv4addr="192.168.244.2", ipv4addrs="[IPv4: configure_for_dhcp="False", ip="192.168.244.2", _ref="record:host_ipv4addr/ZG5zLmhvc3RfYWRkcmVzcyQuMy5jb20ubXJzaG1jLnRlc3QxMTEuMTkyLjE2OC4yNDQuMi4:192.168.244.2/test111.example.com/Internal", ipv4addr="192.168.244.2", host="test111.example.com"]"
```
I've seen an example for another issue that says use low-level API but if we go that route what is the use of update?

Your help is appreciated. Thanks!

**Comment by JonasKs** [comment]
I won’t be on a PC until Tuesday, but I can probably help if you format your code properly so it’s readable on my phone. 
Please format with code blocks instead of quotes. 

```
\`\`\`py 
def some_func():
    ...
\`\`\`
```

**Comment by rainierpineda2** [comment]
Thanks Jonas...I updated the code block

**Comment by JonasKs** [comment]
I’ve never tried to change the IP of an object, and I’m not sure if that possible. I don’t have access to the WAPI doc atm. 

As seen in the source code [here](https://github.com/userlocalhost/infoblox-client/blob/a24ad1a6c97806155c22cbb82c27398e5d413ca4/infoblox_client/objects.py#L186) the explanation for a `shadow_field` says: 

> _shadow_fields - fields that object usually has but they should not be sent to NIOS. These fields can be received from NIOS. Examples: [_ref, is_default]

If we then look at the [host record code](https://github.com/userlocalhost/infoblox-client/blob/a24ad1a6c97806155c22cbb82c27398e5d413ca4/infoblox_client/objects.py#L563), we can see that the field `ipv4addr` is indeed in the shadow field. 

One alternative could be extracting the information you got and creating the host object on the new IP while deleting it from the old.

**Comment by JonasKs** [comment]
Second option would be as you said to use `get_object` and `update_object`. This Is not tested code, and written on my phone so it mat have errors and autocorrect stuff. 
First, make an infoblox connection:
```py
from infoblox_client import connector
opts = {'host': '192.168.1.10', 'username': '<username>', 'password': '<password>'}
conn = connector.Connector(opts)
```

```py
record = conn.get_object(
    'record:host',
    {
        'view':  'External',
        'ipv4addr': '192.168.244.2'
    }
)
print(record)  # check that you get the correct _ref 
conn.update_object(
    record[0]['_ref'],  # use the ref
    {
        'ipv4addr': '192.168.244.3'
    }
)
```

This should work, but as I said I haven’t tested it.

**Comment by rainierpineda2** [comment]
Thanks Jonas. I will try these and let you know.

**Comment by JonasKs** [comment]
Did it work? Please close the issue if it did.

**Comment by rainierpineda** [comment]
Hi Jonas. My test Infoblox has been having issues. I will test ASAP when my access is restored and let you know.

**Comment by rainierpineda2** [comment]
It doesn't seem to like the update
```
infoblox_client.exceptions.InfobloxCannotUpdateObject: Cannot update object with ref record:host/ZG5zLmhvc3QkLjMuY29tLm1yc2htYy5kZWYxMjM:def123.mrshmc.com/Internal: { "Error": "AdmConProtoError: Field is not writable: ipv4addr", 
  "code": "Client.Ibap.Proto", 
  "text": "Field is not writable: ipv4addr"
} [code 400]
```

**Comment by JonasKs** [comment]
Then you will have to delete and re-create it. Let me know if you need more help.

**Comment by rainierpineda** [comment]
Thanks Jonas. I guess that is the only way. You may close this thread.

**Comment by JonasKs** [comment]
I’m not an Infoblox employee, I just happened to see your post, hehe. You will have to close this yourself :)
