### ISSUE TITLE
FixedAddress doesn't have a 'name' field

### ISSUE THREAD

**Issue by mdzhigarov** [infobloxopen/infoblox-client#221]
The objects.FixedAddress (v4 & v6) doesn't have a 'name' field.
This makes it impossible to create a fixed address with populated name in Infoblox.

**Comment by JonasKs** [comment]
You can use the `create_object` to do everything the high level don't support.

```py
from infoblox_client import connector
from infoblox_client import objects

opts = {'host': '192.168.1.10', 'username': 'admin', 'password': 'admin'}
conn = connector.Connector(opts)

args = [
    'fixedaddress',
    {
        'network': '192.168.0.0/24',
        'ipv4addr': '192.168.0.1',
        'mac': '00:00:00:00:00:00',
        'name': 'My_name_test'
    }
    ]
conn.create_object(*args)
```

**Comment by mdzhigarov** [comment]
Yes, I know there is a workaround. But it doesn't hurt to add the "name" field to the FixedAddress directly

**Comment by JonasKs** [comment]
This repo seems to be dead with the exception of pull requests, unfortunately.

**Comment by saiprasannasastry** [comment]
will add this

**Comment by saiprasannasastry** [comment]
closing this as name field has been added
