### ISSUE TITLE
Extensible attributes to be optionally updated/modified rather than replaced

### ISSUE THREAD

**Issue by noziwatele** [infobloxopen/infoblox-client#233]
It would be great if extensible attributes on objects could be updated rather than replaced. The WAPI has a method for this with extattrs+/- which will add or remove an attribute from the set without affecting other attributes.

E.g.

```
"extattrs+": {
             "attrstring": {"value": "new string"}
             }
```

I see that some work has been done towards this in the past, but it doesn't seem to work anymore. Ref #66 

When I do the following:

```
network = objects.Network.search(connector=conn, network='10.0.0.0/24', network_view='default', return_fields=['network', 'extattrs'])

ea = objects.EA({'Attrib1': 'value1', 'Attrib2': 'value2'})

network.extattrs = ea

network.update()
```
... it replaces any existing extensible attributes.

There are work arounds, like grabbing the existing attributes and appending/modifying them, then writing them back, but this is cumbersome in higher-level tools such as Ansible.

**Comment by saiprasannasastry** [comment]
@noziwatele  quite a busy schedule this week, will definitely look into it and try providing the fix :)

**Comment by saiprasannasastry** [comment]
@noziwatele  youre saying that when you do update, it removes all the present ones and add new ones that are passed?

**Comment by saiprasannasastry** [comment]
also i think you are making an objects call, try making this function call from object_manager
update_network_options('10.0.0.0/24',ea)

**Comment by JonasKs** [comment]
Infoblox defaults to overwriting unless you update with the `+` sign.(`{“extattrs+” {...}}`) This is only true for newer versions of Infoblox I believe, so a version check would have to be implemented.

**Comment by sarya-infoblox** [comment]
Hi @noziwatele Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.
