### ISSUE TITLE
Auth regression between 0.4.22 and 0.4.23

### ISSUE THREAD

**Issue by nbartos** [infobloxopen/infoblox-client#236]
After this commit:  https://github.com/infobloxopen/infoblox-client/commit/d85e570f6540efcd20c404897101a56c4257876a

I am able to login, but unable to perform write operations.

Example test script:
```
#!/usr/bin/env python3
  
from infoblox_client import connector
from infoblox_client import objects

params = {
    'host': 'some-hostname',
    'username': 'some-username',
    'password': 'some-password',
}

record = 'some.domain.example.com'

conn = connector.Connector(params)
existing = objects.ARecord.search(conn, name=record)
if existing:
    existing.delete()
objects.ARecord.create(conn, name=record, ip='1.2.3.4', ttl=60)
```

Traceback:
```
Traceback (most recent call last):
  File "/home/ubuntu/c.py", line 15, in <module>
    existing = objects.ARecord.search(conn, name=record)
  File "/home/ubuntu/r/infoblox-client/foo/lib/python3.7/site-packages/infoblox_client/objects.py", line 365, in search
    connector, **kwargs)
  File "/home/ubuntu/r/infoblox-client/foo/lib/python3.7/site-packages/infoblox_client/objects.py", line 359, in _search
    max_results=max_results)
  File "/home/ubuntu/r/infoblox-client/foo/lib/python3.7/site-packages/infoblox_client/connector.py", line 49, in callee
    return func(*args, **kwargs)
  File "/home/ubuntu/r/infoblox-client/foo/lib/python3.7/site-packages/infoblox_client/connector.py", line 289, in get_object
    extattrs, proxy_flag=True)
  File "/home/ubuntu/r/infoblox-client/foo/lib/python3.7/site-packages/infoblox_client/connector.py", line 325, in _handle_get_object
    return self._get_object(obj_type, url)
  File "/home/ubuntu/r/infoblox-client/foo/lib/python3.7/site-packages/infoblox_client/connector.py", line 336, in _get_object
    self._validate_authorized(r)
  File "/home/ubuntu/r/infoblox-client/foo/lib/python3.7/site-packages/infoblox_client/connector.py", line 177, in _validate_authorized
    raise ib_ex.InfobloxBadWAPICredential(response='')
infoblox_client.exceptions.InfobloxBadWAPICredential: Infoblox IPAM is misconfigured: infoblox_username and infoblox_password are incorrect.
```

Python 3.7.5rc1

Venv list:
```
Babel==2.7.0
certifi==2019.9.11
chardet==3.0.4
debtcollector==1.22.0
idna==2.8
infoblox-client==0.4.23
iso8601==0.1.12
msgpack==0.6.2
netaddr==0.7.19
netifaces==0.10.9
oslo.config==6.11.1
oslo.context==2.23.0
oslo.i18n==3.24.0
oslo.log==3.44.1
oslo.serialization==2.29.2
oslo.utils==3.41.2
pbr==5.4.3
pkg-resources==0.0.0
pyinotify==0.9.6
pyparsing==2.4.2
python-dateutil==2.8.0
pytz==2019.3
PyYAML==5.1.2
requests==2.22.0
rfc3986==1.3.2
six==1.12.0
stevedore==1.31.0
urllib3==1.25.6
wrapt==1.11.2
```

**Comment by JonasKs** [comment]
Your traceback say:
```
Infoblox IPAM is misconfigured: infoblox_username and infoblox_password are incorrect.
```
I’d start there

**Comment by nbartos** [comment]
The credentials and host are all correct.  Everything works perfectly when reverting commit https://github.com/infobloxopen/infoblox-client/commit/d85e570f6540efcd20c404897101a56c4257876a .

**Comment by nbartos** [comment]
Interestingly, when setting HTTP_PROXY to a squid proxy, it works after that commit.  I'm a bit baffled on what is going on there.

**Comment by JonasKs** [comment]
Hmm, strange. I'm not using any proxy, using Python3.8 and newest version without any issues. 
Can you go into your `venv/lib/python3.7/site-packages/infoblox-client/connector.py` and actually print the response on line `175`? Since the exception gives no indicator, it's hard to troubleshoot.
```py
    @staticmethod
    def _validate_authorized(response):
        print(response.json())  # <--------
        if response.status_code == requests.codes.UNAUTHORIZED:
            raise ib_ex.InfobloxBadWAPICredential(response='')
```

**Comment by nbartos** [comment]
I printed response.text and got this:
```
Exception: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Authorization Required</title>
</head><body>
<h1>Authorization Required</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

As far as wapi_version goes, I could only go up to 2.9, 2.10 was not supported.  It didn't seem to change anything.

**Comment by nbartos** [comment]
I think I may know what is going on.  When the auth is performed, following requests that use the same cookie need to come from the same source IP address?  If I print out the requests, I see in the cookie the "ip=" entry changes.  In 0.4.22, it seems that there are more times where a cookie is created than in 0.4.23.  I believe there may be a load balancer or reverse proxy between the client and the infoblox device, so a new tcp connection might come from a different source IP address.  That would explain why it works going through a squid proxy that is near the infoblox device, because the final http request from that proxy to the infoblox device would have a consistent IP address between requests.

**Comment by pieterdejaeghere** [comment]
We are facing the exact same error after an upgrade from 0.4.20 -> 0.4.23. We integrated this package into a long-living daemon. Soon after a restart everything works, but after a while, auth fails. I'm assuming this is because the cookie expires after a while, and this code assumes it won't expire. Without a fix for this case, we're stuck on 0.4.22

**Comment by AmbicaY** [comment]
We are also facing the same problem. On restart of the app, it works fine, but after sometime, it fails with the same error above.

**Comment by jobec** [comment]
**Any chance this will ever get fixed?** Reverting commit d85e570 or extending it to catch authentication errors shouldn't be that difficult. In it's current state, releases post 0.4.22 are rather useless.

Or is this client abandoned?

**Comment by sarya-infoblox** [comment]
Hi @nbartos are you still facing this issue?

**Comment by nbartos** [comment]
I'm no longer working on a project that uses infoblox, so I can't tell you if the problem persists.

**Comment by jobec** [comment]
I am still facing this issue.
Like I said, as long as commit https://github.com/infobloxopen/infoblox-client/commit/d85e570f6540efcd20c404897101a56c4257876a isn't reversed or authentication errors are not caught, this module has become unusable in long running daemons.

**Comment by mr-oz-09** [comment]
> I am still facing this issue. Like I said, as long as commit [d85e570](https://github.com/infobloxopen/infoblox-client/commit/d85e570f6540efcd20c404897101a56c4257876a) isn't reversed or authentication errors are not caught, this module has become unusable in long running daemons.

I can also confirm, I am experiencing this issue with the latest release.

**Comment by sarya-infoblox** [comment]
Hi @jobec @mr-oz-09, we will look into this issue in our next release. I would suggest you use the latest release 0.6.0.

**Comment by liijuun** [comment]
I'm using infoblox-client 0.6.0,  python version 3.9.9. I still get this issue. 


```
  from infoblox_client import connector
  
  opts = {'host': 'xxx', 'wapi_version': '2.12.1', 'username': r"xxx", 'password': r"xxx"}
  conn = connector.Connector(opts)
  print(conn.wapi_url)
  network_views = conn.get_object('networkview')
  print(network_views)


C:\Python\Python39\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.228.254.152'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "C:\workspace\work\code\libqtest\netops\infoblox.py", line 33, in <module>
    network_views = conn.get_object('networkview')
  File "C:\Python\Python39\lib\site-packages\infoblox_client\connector.py", line 53, in callee
    return func(*args, **kwargs)
  File "C:\Python\Python39\lib\site-packages\infoblox_client\connector.py", line 317, in get_object
    return self._handle_get_object(obj_type, query_params, extattrs,
  File "C:\Python\Python39\lib\site-packages\infoblox_client\connector.py", line 354, in _handle_get_object
    return self._get_object(obj_type, url)
  File "C:\Python\Python39\lib\site-packages\infoblox_client\connector.py", line 365, in _get_object
    self._validate_authorized(r)
  File "C:\Python\Python39\lib\site-packages\infoblox_client\connector.py", line 210, in _validate_authorized
    raise ib_ex.InfobloxBadWAPICredential(response='')
infoblox_client.exceptions.InfobloxBadWAPICredential: Infoblox IPAM is misconfigured: infoblox_username and infoblox_password are incorrect.

```

And i try to use requests.get directly, i get the error also:
```
import requests
from requests.auth import HTTPBasicAuth

# Set the URL for the Infoblox API
hostname = ""
url = "https://xxx/wapi/v2.12.1/networkview"

# Set the headers for the API request
headers = {
    "Content-Type": "application/json",
    "Accept": "application/json"
}

# Send the GET request to the API
response = requests.get(url, headers=headers, verify=False, auth=HTTPBasicAuth('xxxx', 'xxxx'))

print(response.status_code)
print(response.text)

401
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Authorization Required</title>
</head><body>
<h1>Authorization Required</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

Do you have any suggestion?  Thanks.
