### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by serbaniuliuscezar** [infobloxopen/infoblox-client#240]
As Python2 will officially be EOL in 2 weeks, does it make sense to refactor the code so as to remove legacy code that is not used by Python3? Stuff like having classes inherit base object.

**Comment by saiprasannasastry** [comment]
It would take quite some effort to refactor. Need to talk to manager and get back

**Comment by tadeboro** [comment]
Please do note that this library is used by Ansible NIOS modules. Removing support for Python 2 might render them unusable on systems that do not have Python 3 installed (for example, RHEL 7 comes with Python 2 installed by default and is supported until 2024).

**Comment by saiprasannasastry** [comment]
@tadeboro  right now there are no plans of removing python2 support because of anisble and openstack plugins :)

**Comment by serbaniuliuscezar** [comment]
Oh, wow, I did not know that. Legacy software :(

Then maybe we'll check again in 2024 💯
