### ISSUE TITLE
Restart services

### ISSUE THREAD

**Issue by jonnic** [infobloxopen/infoblox-client#242]
Is it possible to restart the DHCP service through this client library? If so is there an example available.

Thanks,

**Comment by JonasKs** [comment]
Is it possible through the WAPI? If so, yes, if not, no. Check `yourinfoblox.url/wapidoc`

**Comment by jonnic** [comment]
Yes, it's possible through wapi, I've used it in the past by using the requests library natively:-
```
grid = self.do_request('GET', 'grid', {})

req_data = json.dumps({
            'member_order': 'SEQUENTIALLY',
            'service_option': 'DNS',
            'restart_option': 'RESTART_IF_NEEDED',
            'sequential_delay': 1})
rq_uri = "{}/{}?_function=restartservices".format(API_URL, grid[0]['_ref'])
rq = self.session.post(rq_uri, data=req_data)
```

however I see in the `object_manager` has a  `restart_all_services` method, but there doesn't appear to be any documentation on how to use it, or examples of it being used elsewhere in the code.

It would be much cleaner to use a pre-defined method than writing my own if one is available.

Looking at the code for `restart_all_services` I believe I need to pass it a member object to restart, however when I try and create a member object, using:-
`m = objects.Member.search_all(conn, name='infoblox-gridmaster')`
I get an error:-
```
Failed on object search with url https://infoblox-gridmastger/wapi/v2.1/member?host_name=infoblox-gridmaster&_return_fields=host_name%2Cipv6_setting%2Cnode_info%2Cvip_setting%2Cextattrs&_proxy_search=GM: b'{ "Error": "AdmConProtoError: Unknown argument/field: \'ipv6_setting\'", \n  "code": "Client.Ibap.Proto", \n  "text": "Unknown argument/field: \'ipv6_setting\'"\n}'

```
Am I doing something wrong here or is this a bug?

**Comment by saiprasannasastry** [comment]
is that your hostname?

**Comment by saiprasannasastry** [comment]
from infoblox_client.object_manager import InfobloxObjectManager

x = InfobloxObjectManager(conn).restart_all_services(member='infoblox.localdomain')
the name should be the hostname of the member

**Comment by jonnic** [comment]
In my example call 'infoblox-gridmaster' is replaced with the FQDN of our gridmaster.

I've tried the example you provided
`x = InfobloxObjectManager(conn).restart_all_services(member='infoblox.localdomain')`

But `restart_all_services` expects a member object not a string, so this errors.

**Comment by jonnic** [comment]
I've found a way to implement it in my application, here `self._iblox` is a infoblox_client.Connector object.
```
    def _request_dhcp_restart(self):
        '''
        Request that the infoblox restarts the DHCP service
        '''
        _grid = self._iblox.get_object('grid')[0]['_ref']
        _payload = {
                    'member_order': 'SEQUENTIALLY',
                    'service_option': 'DHCP',
                    'restart_option': 'RESTART_IF_NEEDED',
                    'sequential_delay': 1 
                   }
        self._iblox.call_func('restartservices', _grid, _payload)
```

**Comment by saiprasannasastry** [comment]
from infoblox_client.object_manager import InfobloxObjectManager
from infoblox_client import connector
from infoblox_client import objects

opts = {'host': '10.120.22.17', 'username': 'admin', 'password': 'infoblox'}
conn = connector.Connector(opts)
y= objects.Member.search(conn,host_name="infoblox.localdomain",
                                                 return_fields=['host_name'])
x = InfobloxObjectManager(conn).restart_all_services(y)

This is how we can restart all services,

**Comment by saiprasannasastry** [comment]
sorry that i commented before trying it out :)

**Comment by saiprasannasastry** [comment]
2/2 we dont have a high level API to implement a single service restart

**Comment by jonnic** [comment]
Thanks!
