### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by JonasKs** [infobloxopen/infoblox-client#245]
Hi,
We've seen 6 PRs over the last months go through without pushing to PyPi. Could a new release be scheduled?
If you'd like to look into doing this through github workflows to do that kind of job, I've implemented that in my project [here](https://github.com/JonasKs/django-guid/blob/master/.github/workflows/publish_to_pypi.yml).

**Comment by saiprasannasastry** [comment]
@JonasKs  was out of office the entire last week, will get these commits pushed, and try to implement something. ALways appreciate your ffedback :)

**Comment by saiprasannasastry** [comment]
pushed
