### ISSUE TITLE
RFE: upgrade WAPI version to something after 2.7

### ISSUE THREAD

**Issue by badnetmask** [infobloxopen/infoblox-client#259]
https://github.com/infobloxopen/infoblox-client/blob/f2eca3579c55dc76732f85cc2be64a33d1b83d62/infoblox_client/connector.py#L73

This is more an RFE than a bug. Over time I have bumped into issues with this library which have been traced back to the fact that it's still using WAPI 2.1, while the latest seems to be 2.11 (NIOS 8.5.0). Some of the stuff I have noticed is, for example, support for DTC or some IPv6 features, which are only available starting from WAPI 2.7.3, which is the latest version which will be EOL'd in June/2020 (along with NIOS 8.2.7).

I could have just submitted a PR to bump the version, but I am not sure what kind of testing needs to be done in order to make sure nothing breaks, hence why I am putting this RFE.

Thank you.

**Comment by AvRajath** [comment]
@badnetmask You can use this 
opts = {'host': '192.168.1.10', 'username': 'admin', 'password': 'admin', 'wapi_version': <required_version>}
conn = connector.Connector(opts)

Bumping up to higher WAPI versions as default would impact customers using older version of NIOS. But you may always use the wapi_version parameter to use the wapi version that you want to.

**Comment by JonasKs** [comment]
Fixed in https://github.com/infobloxopen/infoblox-client/pull/263.
