### ISSUE TITLE
Infoblox authentication errors - cookie issue

### ISSUE THREAD

**Issue by GKaren001** [infobloxopen/infoblox-client#266]
We integrated Infoblox-client with a continuous running daemon. 
Initially the connection to Infoblox works fine and all the requests go through but after leaving the daemon running for over 10 minutes , the authentication fails with below error.

_Infoblox IPAM is misconfigured: infoblox_username and infoblox_password are incorrect._

This seems to be caused by the cooking expiration. Any suggestions for workarounds until we implement self-signed certificates?

Thanks,

**Comment by IngmarVG-IB** [comment]
The default account time-outs are 360s which matches what you are seeing. You can set that timer to a higher value or include a check for session validity into your daemon.

**Comment by shashankbansal6** [comment]
I have the same issue. I set the following config: 
```
opts = {
    'host'                 : inf.host,
    'username'             : inf.user,
    'password'             : inf.password,
    'http_request_timeout' : None,
    'wapi_version'         : '2.9.1',
    'ssl_verify'           : False
}
```
From what I understand setting `http_request_timeout : None` should set this value to never timeout right?

**Comment by JonasKs** [comment]
To me, it seems like the message you get is provided by the `InfobloxBadWAPICredential`, which again is only raided by `if response.status_code == requests.codes.UNAUTHORIZED`, so the session time out seems to be on the Infoblox side of things. Which again means that you have to handle it in some other way. A non-DRY example to just give you a hint below:

```py
from infoblox_client.objects import NetworkV4
from infoblox_client.connector import Connector

try: 
    NetworkV4.create(conneciton=connection, cidr='192.168.0.0/24')
except InfobloxBadWAPICredential:
    connection = Connector(...)
    NetworkV4.create(conneciton=connection, cidr='192.168.0.0/24')
```

**Comment by shashankbansal6** [comment]
Sorry about the logs. You are right, I had a misunderstanding about the `http_request_timeout`. I have fixed that. As for the session persistence goes, as a more long term solution I guess I need to add a logic to refresh sessions every few hours. 
In any case, thanks for the help and explanation.

**Comment by shashankbansal6** [comment]
Btw if anyone else had the same issue, this was my solution:

```
from timeloop import Timeloop

tl = Timeloop()

@tl.job(interval=timedelta(seconds=300))
def restart_session():
    global ib, FIELDS
    logger.info("Refreshing infoblox-client connection")
    
    opts = {
        'host'                 : inf.host,
        'username'             : inf.user,
        'password'             : inf.password,
        'http_request_timeout' : 30,
        'wapi_version'         : '2.9.1'
    }

    ib = connector.Connector(opts)
    FIELDS = ['comment','extattrs','network']

if __name__=="__main__":
    opts = {
        'host'                 : inf.host,
        'username'             : inf.user,
        'password'             : inf.password,
        'http_request_timeout' : 30,
        'wapi_version'         : '2.9.1',
        'max_retries'          : 5
    }
    ib = connector.Connector(opts)
    FIELDS = ['comment','extattrs','network']
    
    tl.start()
    try:
        < Use IB-CLIENT for whatever you are using 
        tl.stop()
    
    except Exception as err:
        logger.error(err, exc_info=True)
        tl.stop()
    
```

**Comment by sarya-infoblox** [comment]
Hi @GKaren001, does the above solution resolves your issue?

**Comment by sarya-infoblox** [comment]
Hi @GKaren001 Can you please confirm if we can close this issue or you need help?

**Comment by GKaren001** [comment]
Yes , please close the ticket.

**Comment by sarya-infoblox** [comment]
Closing the issue.
