### ISSUE TITLE
How to add multiple IP addresses to host record

### ISSUE THREAD

**Issue by piwigit** [infobloxopen/infoblox-client#269]
Hi guys.

How can I add multiple IP addresses to one host record using the high level API objects? 

The documentation says:

**Create a host record:**
```
my_ip = objects.IP.create(ip='192.168.1.25', mac='aa:bb:cc:11:22:33')
hr = objects.HostRecord.create(conn, view='my_dns_view',
                               name='my_host_record.my_zone.com', ip=my_ip)
```

That's working like a charm. But I want to add a second, third ... IP address to that host record without overwriting existing addresses and I didn't figure out how. May you please help?

Thanks in advance.

**Comment by IngmarVG-IB** [comment]
use "ips" instead of "ip" see objects.py line 13383

my_ip = objects.IP.create(ip='192.168.1.25', mac='aa:bb:cc:11:22:33')
versus
my_ip = objects.IP.create(ips=['192.168.1.25','192.168.1.26'], mac='aa:bb:cc:11:22:33')

**Comment by sarya-infoblox** [comment]
Hi @piwigit does the above solution resolves your issue?

**Comment by sarya-infoblox** [comment]
Hi @piwigit Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.
