### ISSUE TITLE
Typo when adding extattrs in _construct_url, resulting in "Unknown extensible attribute" error

### ISSUE THREAD

**Issue by antoinedelia** [infobloxopen/infoblox-client#271]
When we try to add `extattrs` to a request, it goes into the `_construct_url` and get added to the query params.

However, there is a little star when adding the key as seen below:

https://github.com/infobloxopen/infoblox-client/blob/a705e7335c43ac0ea686e9414291781109ea7e57/infoblox_client/connector.py#L153

This produces an error when trying to make the request:

```python
extattrs = {
    "alias": {
        "value": "foo.bar.com"
    }
}
    
client.get_object('record:host', extattrs=extattrs)
```

Url used to make the request:
> https://infoblox.eu.airbus.corp/wapi/v2.9/record:host?*alias=foo.bar.com

Error:
> Unknown extensible attribute: alias

However, when we remove the star, we get the expected results.

Could it be possible to remove this star to make the `extattrs` works?

Thanks a lot.

**Comment by JonasKs** [comment]
Have you tried the approach seen in the [README.md](https://github.com/infobloxopen/infoblox-client#more-examples)?

**Comment by antoinedelia** [comment]
Hello Jonas,

I just tried the exact code from the exemples you linked. I just replaced the `extensible_attribute` with "alias" and `value` by "foo.bar.com", but I got the exact same error as before.

**Comment by antoinedelia** [comment]
Okay, it appears that we can use the `payload` parameter to populate the query params.

So in the end, I was able to make everything works like this:

```python
payload = {
    "alias": "foo.bar.com"
}
    
client.get_object('record:host', payload=payload)
```

This works as expected!
