### ISSUE TITLE
connector.Connector does not support client certificates

### ISSUE THREAD

**Issue by jbakermk** [infobloxopen/infoblox-client#274]
The Connector assumes use of a username/password and does not allow a path to a certificate and key in order to configure the requests session. This can be achieved as follows:

1. Document a new option to Connector called cert, a tuple (path_to_cert, path_to_key).
2. Adjust _configure_options so username/password are only required if an option cert is not given, and set self.cert = options['cert'].
2. Adjust _configure_session to set self.session.cert= self.cert if self.cert is not None, else set self.session.auth = (user, pass).
3. Adjust _get_request_options add options['cert']= self.cert if self.cert is not None.

**Comment by sarya-infoblox** [comment]
Hi @jbakermk, Can you provide an example where you are using client certificates.

**Comment by sarya-infoblox** [comment]
Hi @jbakermk, we are preparing a plugin release soon, and if you could provide an example where you are using client certificate and your use case. we might be able to provide the solution in next release.

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.
