### ISSUE TITLE
broken in python3.7.9

### ISSUE THREAD

**Issue by pastephens** [infobloxopen/infoblox-client#275]
**sudo pip3 install infoblox-client**
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting infoblox-client
  Using cached https://files.pythonhosted.org/packages/86/68/d154a4a3e549fbebb0922a721ce3a638c66c82fc486027433d0163744fdb/infoblox_client-0.5.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=17.1 in /usr/local/lib/python3.7/site-packages (from infoblox-client)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.7/site-packages (from infoblox-client)
Collecting oslo.log>=1.8.0 (from infoblox-client)
  Using cached https://files.pythonhosted.org/packages/c3/1e/60b04b46c59d1bcfd31191075b8b4c4c2e9aa870349c1f209f4782ca0253/oslo.log-4.4.0-py3-none-any.whl
Collecting oslo.serialization>=1.4.0 (from infoblox-client)
  Using cached https://files.pythonhosted.org/packages/ed/a6/74b862d3481119df70d7b00206373a6c196fc50a9771ccf727e9d544623a/oslo.serialization-4.0.1-py3-none-any.whl
Requirement already satisfied: urllib3>=1.13 in /usr/local/lib/python3.7/site-packages (from infoblox-client)
Requirement already satisfied: requests>=2.5.2 in /usr/local/lib/python3.7/site-packages (from infoblox-client)
Collecting oslo.config>=5.2.0 (from oslo.log>=1.8.0->infoblox-client)
  Using cached https://files.pythonhosted.org/packages/c9/44/086eddcda438416a6bb9ce652f83d5e2ce539d18c23037cbdc7055a734fb/oslo.config-8.4.0-py3-none-any.whl
Collecting oslo.context>=2.20.0 (from oslo.log>=1.8.0->infoblox-client)
  Using cached https://files.pythonhosted.org/packages/d5/72/72efa945e23daa99c0b6dd46643c7eb0e4c3224eff01da4d11b6f0210777/oslo.context-3.1.1-py3-none-any.whl
Requirement already satisfied: debtcollector>=1.19.0 in /usr/local/lib/python3.7/site-packages (from oslo.log>=1.8.0->infoblox-client)
Requirement already satisfied: oslo.i18n>=3.20.0 in /usr/local/lib/python3.7/site-packages (from oslo.log>=1.8.0->infoblox-client)
Collecting oslo.utils>=3.36.0 (from oslo.log>=1.8.0->infoblox-client)
  Using cached https://files.pythonhosted.org/packages/c6/35/e43e70ca33dcbf15880aef82ba2a100edbee6e9d1a50ed4d5defc5c451fa/oslo.utils-4.7.0-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.7/site-packages (from oslo.log>=1.8.0->infoblox-client)
Collecting pyinotify>=0.9.6; sys_platform != "win32" and sys_platform != "darwin" and sys_platform != "sunos5" (from oslo.log>=1.8.0->infoblox-client)
  Using cached https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz
Requirement already satisfied: pbr>=3.1.1 in /usr/local/lib/python3.7/site-packages (from oslo.log>=1.8.0->infoblox-client)
Requirement already satisfied: msgpack>=0.5.2 in /usr/local/lib64/python3.7/site-packages (from oslo.serialization>=1.4.0->infoblox-client)
Requirement already satisfied: pytz>=2013.6 in /usr/local/lib/python3.7/site-packages (from oslo.serialization>=1.4.0->infoblox-client)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.5.2->infoblox-client)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.5.2->infoblox-client)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.5.2->infoblox-client)
Collecting rfc3986>=1.2.0 (from oslo.config>=5.2.0->oslo.log>=1.8.0->infoblox-client)
  Using cached https://files.pythonhosted.org/packages/78/be/7b8b99fd74ff5684225f50dd0e865393d2265656ef3b4ba9eaaaffe622b8/rfc3986-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: netaddr>=0.7.18 in /usr/local/lib/python3.7/site-packages (from oslo.config>=5.2.0->oslo.log>=1.8.0->infoblox-client)
Requirement already satisfied: importlib-metadata>=1.7.0; python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from oslo.config>=5.2.0->oslo.log>=1.8.0->infoblox-client)
Collecting stevedore>=1.20.0 (from oslo.config>=5.2.0->oslo.log>=1.8.0->infoblox-client)
  Using cached https://files.pythonhosted.org/packages/d4/49/b602307aeac3df3384ff1fcd05da9c0376c622a6c48bb5325f28ab165b57/stevedore-3.3.0-py3-none-any.whl
Requirement already satisfied: PyYAML>=3.12 in /usr/local/lib64/python3.7/site-packages (from oslo.config>=5.2.0->oslo.log>=1.8.0->infoblox-client)
Requirement already satisfied: wrapt>=1.7.0 in /usr/local/lib/python3.7/site-packages (from debtcollector>=1.19.0->oslo.log>=1.8.0->infoblox-client)
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.7/site-packages (from oslo.utils>=3.36.0->oslo.log>=1.8.0->infoblox-client)
Collecting netifaces>=0.10.4 (from oslo.utils>=3.36.0->oslo.log>=1.8.0->infoblox-client)
  Using cached https://files.pythonhosted.org/packages/0d/18/fd6e9c71a35b67a73160ec80a49da63d1eed2d2055054cc2995714949132/netifaces-0.10.9.tar.gz
Requirement already satisfied: iso8601>=0.1.11 in /usr/local/lib/python3.7/site-packages (from oslo.utils>=3.36.0->oslo.log>=1.8.0->infoblox-client)
Requirement already satisfied: packaging>=20.4 in /usr/local/lib/python3.7/site-packages (from oslo.utils>=3.36.0->oslo.log>=1.8.0->infoblox-client)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata>=1.7.0; python_version < "3.8"->oslo.config>=5.2.0->oslo.log>=1.8.0->infoblox-client)
Installing collected packages: rfc3986, stevedore, oslo.config, oslo.context, netifaces, oslo.utils, pyinotify, oslo.serialization, oslo.log, infoblox-client
  Running setup.py install for netifaces ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cvphmb2a/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rolo7_bp-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    checking for getifaddrs...found.
    checking for getnameinfo...found.
    checking for IPv6 socket IOCTLs...not found.
    checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h netrose/rose.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h.
    checking whether struct sockaddr has a length field...no.
    checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un rose ash ec ll atmpvc atmsvc dn irda llc.
    checking for routing socket support...no.
    checking for sysctl(CTL_NET...) support...no.
    checking for netlink support...yes.
    will use netlink to read routing table
    building 'netifaces' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNETIFACES_VERSION=0.10.9 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_NETROSE_ROSE_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ROSE=1 -DHAVE_SOCKADDR_ASH=1 -DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/usr/include/python3.7m -c netifaces.c -o build/temp.linux-x86_64-3.7/netifaces.o
    netifaces.c:1:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cvphmb2a/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rolo7_bp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cvphmb2a/netifaces/

**Comment by JonasKs** [comment]
Operating system? This isn't Infoblox that fails to install, its `netifaces`. On ubuntu/fedora you need `python-dev`, and Arch/CentOS/RHEL you need `python-devel`.

**Comment by pastephens** [comment]
RHEL7.

Thanks!
