### ISSUE TITLE
New Release Date

### ISSUE THREAD

**Issue by ExaneServerTeam** [infobloxopen/infoblox-client#299]
Hello,

It's almost two years without a release on the project.
Any ETA for the next release?

I have indeed on my end at least one bug in the last release that keep me using it
and having to maintain a custom tree for deployment.

Regards,
Frédéric

**Comment by sarya-infoblox** [comment]
Hi @ExaneServerTeam Can you please elaborate the bug in detail.

Also, we are collecting all the information about issues, enhancement and will be planning for next release soon.

**Comment by ExaneServerTeam** [comment]
Hello,

The two bugs (Corrected) I am concerned with / used in my day to day workflows:

https://github.com/infobloxopen/infoblox-client/commit/2c9dd6a3aaab8408f0e3131232cbb8da30b1be92
https://github.com/infobloxopen/infoblox-client/commit/1e77c410099dc2765ca5075348149ab6bdc3c2ba

Regards,
Frédéric

**Comment by sarya-infoblox** [comment]
Hi Frédéric,
The commit id 1e77c41 is already merged to master branch.
we are planning for our new release and will merge 2c9dd6a in that.

**Comment by sarya-infoblox** [comment]
Hi Frédéric,
we have merged the above mentioned commits and 
Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.

**Comment by ExaneServerTeam** [comment]
Sorry, back from hollidays. All good on my end as the two commit have been merged & will be available in 0.5.1.
