### ISSUE TITLE
Question: Handling paging with get_object

### ISSUE THREAD

**Issue by gavmckee80** [infobloxopen/infoblox-client#302]
Hi,

I am making a request using get_object(obj_type='record:a',paging=True,max_results=500)

How do I get the next set of results from this object until there are no more results?

Thanks

Gav

**Comment by sarya-infoblox** [comment]
Hi @gavmckee80 you can enter on your command prompt to view the next set of results.

Also, max_results and paging is defined as below:
max_results   (int): Maximum number of objects to be returned.
        If set to a negative number the appliance will return an error
        when the number of returned objects would exceed the setting.
        The default is -1000. If this is set to a positive number,
        the results will be truncated when necessary.
    paging    (bool): Enables paging to wapi calls if paging = True,
        it uses _max_results to set paging size of the wapi calls.
        If _max_results is negative it will take paging size as 1000.

**Comment by sarya-infoblox** [comment]
Hi @gavmckee80 Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.
