### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by arezazadeh** [infobloxopen/infoblox-client#304]
Hi All, 

I have a big task on my plate, which i have to go to ~ 3000 networks and change their "member assignment" to a different ip/member. 

i have been looking around but cant find the correct end-point for this. 

any help is highly appreciate it!
Thanks,
Ahmad.

**Comment by sarya-infoblox** [comment]
Hi @arezazadeh we are working on your request, will get back to you soon.

**Comment by sarya-infoblox** [comment]
Hi @arezazadeh ,
you can try changing member assignment with the wapi calls. below is the example for that-

curl -k -u <username>:<password> -H 'content-type:application/json' -X PUT "https://<ip_address>/wapi/v2.11/network/<Ref_id_of_the_network>:<ip_address>/<cidr>/<view_name>" -d '{"members": [{"_struct": "dhcpmember", "name": "i<member_assignment>"}]}'

Let me know if this helps?

**Comment by sarya-infoblox** [comment]
Hi, 

Closing the issue as there is no further response.
