### ISSUE TITLE
Create tag for release 0.5.1 and corresponding pypi packages

### ISSUE THREAD

**Issue by rubin55** [infobloxopen/infoblox-client#315]
Hi, I noticed there has been some recent work on a release 0.5.1, merged here:

https://github.com/infobloxopen/infoblox-client/commit/4ff68e0b7f346134984591468371ae4a2cf17dfe

I interpret that as 0.5.1 being released. However, I don't see a tag for version 0.5.1 yet, and no corresponding PyPi packages on https://pypi.org/project/infoblox-client/

Can you guys (further) release 0.5.1?

**Comment by rubin55** [comment]
Do you know if the current stable version (0.5.0) should work for most cases against NIOS 8.5 (wapi v2.11.3)? Any caveats I should be aware of?

**Comment by sarya-infoblox** [comment]
Hi @rubin55 

Infoblox client (0.5.0) stable version is working fine with NIOS 8.6.1. If you observe any issues with that please raise them on the issues page of Infoblox-client Github.

**Comment by sarya-infoblox** [comment]
Hi @rubin55 

We are working on a new release right now and will release a new version soon. Closing this issue.
