### ISSUE TITLE
Automation Platform 2.x - infoblox-client is required but does not appear to be installed

### ISSUE THREAD

**Issue by gcoronae** [infobloxopen/infoblox-client#324]
Not sure why Automation Platform Controller doesn't see the client under the default install.

Location: /usr/local/lib/python3.8/site-packages

**Comment by sarya-infoblox** [comment]
Hi @gcoronae 

We are working on a new release right now, we will look at this issue as soon as we get time.

**Comment by sarya-infoblox** [comment]
Hi @gcoronae,

Can you provide some more details and try cmd 'python3.8 -m pip install infoblox-client'
and verify whether the package is available or not if not then we will have a look.

**Comment by gcoronae** [comment]
Hi Stuti Arya,

Thank you for the follow up.  Since my inquiry I've learned the necessity
of  Execution Environments in Ansible Automation Platform.  I'm building
our own containers with all the dependencies needed to run Infoblox
collection/modules.

Thank you!
Gus

**Comment by sarya-infoblox** [comment]
Hi @gcoronae, do you need any further help or should I proceed with issue closure?

**Comment by gcoronae** [comment]
Hi, please proceed and close the issue.  Thank you!

**Comment by sarya-infoblox** [comment]
Closing this issue.
