### ISSUE TITLE
AdmConProtoError: Unknown object type (record:ns)

### ISSUE THREAD

**Issue by Guxing0321** [infobloxopen/infoblox-client#326]
Hi Team, 

I have tried to add ns record with the code below

```python
try:
    res, isOk = objects.NsRecord.create_check_exists(self.conn, view='default', name=record_name,
                                                     address={'_struct': 'zonenameserver',
                                                                 'address': record},)
except InfobloxCannotCreateObject as e:
    logger.error(str(e))
    return "add NS record err: {e}".format(e=str(e)), False
```

And it shows error below

```python

 Cannot create \'record:ns\' object(s): b\'{ "Error": "AdmConProtoError: Unknown object type (record:ns)", \\n  "code": "Client.Ibap.Proto", \\n  "text": "Unknown objec (record:ns)"\\n}\' [code 400]',
 False)

```

Could you please give me some advice on it ?

BR
Robin

**Comment by Guxing0321** [comment]
hello team, 

Any response?


BR
Robin

**Comment by sarya-infoblox** [comment]
Hi @Guxing0321,

You are using the wrong syntax please use-

res, isOk = objects.NsRecord.create_check_exists(conn, view='default',  nameserver='new_my_zone.com', addresses=[{
                                                                 'address': '10.0.0.6'}] )


Let me know if this helps.

**Comment by Guxing0321** [comment]
Hello @sarya-infoblox ,

Sorry for the late response,  your advice is great help for me.
And now the issue is resolved

BR
Robin
