### ISSUE TITLE
Python3.9 crashes with infoblox-client

### ISSUE THREAD

**Issue by itinneed2022** [infobloxopen/infoblox-client#333]
On any run using the infoblox-client, I receive the following:
redirecting (type: lookup) ansible.builtin.nios_next_ip to community.general.nios_next_ip
redirecting (type: lookup) community.general.nios_next_ip to infoblox.nios_modules.nios_next_ip
objc[1816]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[1816]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state

To get that I ran: ansible-playbook get_dns_from_infoblox.yaml -i ./hosts -vvv

Ansible 2.13.2
Python 3.9.13
Executable Location       /opt/homebrew/bin/ansible-playbook
Python Location              /opt/homebrew/lib/python3.9/site-packages/ansible
infoblox-client location:  /opt/homebrew/lib/python3.9/site-packages

**Comment by sarya-infoblox** [comment]
Hi @itinneed2022 , we are not providing support for python 3.9 right now, suggesting you use python 3.8. Hence closing the issue.
