### ISSUE TITLE
cant create network : AdmConProtoError

### ISSUE THREAD

**Issue by thesutex** [infobloxopen/infoblox-client#351]
after upgrading from 0.5.0 ansible fails when creating network. 

ansible snippet:
      - name: Create a network
        community.general.nios_network:
          network: "{{ networkaddr[0] }}"
          comment: "{{ network_name }}"
          state: present
          provider: "{{ {'host': nioshost, 'username': niosuser, 'password': niospassword} }}"

error: 
{ "Error": "AdmConProtoError: Field is not readable: template", \n  "code": "Client.Ibap.Proto", \n  "text": "Field is not readable: template"\n}

Failed on object search with url https://infoblox/wapi/v2.1/network?network=10.45.64.80%2F28&network_view=default&_return_fields=network%2Cnetwork_view%2Coptions%2Ctemplate%2Cextattrs%2Ccomment&_max_results=1000

HTTPError: 400 Client Error: Bad Request for url: https://infoblox/wapi/v2.1/network?network=10.45.64.80%2F28&network_view=default&_return_fields=network%2Cnetwork_view%2Coptions%2Ctemplate%2Cextattrs%2Ccomment&_max_results=1000

**Comment by hemanthKa677** [comment]
Can you please let me know, what is the version of ansible modules , you are running on? And please do share me of infoblox-client version.

**Comment by hemanthKa677** [comment]
We have fixed that bug create because of template which is non searchable field. Please install latest version of both ansible and infoblox-client. And try checking the create network.

**Comment by sarya-infoblox** [comment]
Closing this ticket as there is no response from the user.
