### ISSUE TITLE
Readme - docs link is broken 

### ISSUE THREAD

**Issue by emosher** [infobloxopen/infoblox-client#40]
![infoblox-docs](https://cloud.githubusercontent.com/assets/1850338/11860900/2facc2ba-a448-11e5-86ff-eb19d0581fdd.png)

The link in the readme to documentation shows me the above page.  I'd be happy to submit a PR if you point me to the right link, otherwise I'm going thru the docs folder and readme to see what I can pick up.  Thanks.

**Comment by bondar-pavel** [comment]
@emosher, thanks for reporting it!
I will work on populating documentation to readthedocs.org.
For now you can start with README, and in the meantime I'll try to improve overall level of documentation.

**Comment by bondar-pavel** [comment]
Integrated infoblox-client with readthedocs.org.
Now documentation is available http://infoblox-client.readthedocs.org/en/latest/
![image](https://cloud.githubusercontent.com/assets/2071117/11865030/5cac19ae-a4b2-11e5-95d0-271685c7b8ab.png)

**Comment by emosher** [comment]
@bondar-pavel Awesome, thanks!
