### ISSUE TITLE
_ref attribute error

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#43]
I created a dhcp member like this.

        ib_dhcp_members = []
        for m in dhcp_members:
            ib_dhcp_members.append(ib_objects.AnyMember(_struct='dhcpmember',
                                                        name=m.member_name))

Then I call the following to restart dhcp members.

        for ib_member in self.ib_cxt.mapping.ib_dhcp_members:
            self.ib_cxt.ibom.restart_all_services(ib_member)

Then this fails because the following method checks _ref property which is not created.

    def restart_all_services(self, member):
        if not member._ref:             <== FAILURE
            member.fetch()
        self.connector.call_func('restartservices', member._ref,
                                 {'restart_option': 'RESTART_IF_NEEDED',
                                  'service_option': 'ALL'})

You either need to create all the mandatory fields with default values when an object is created or
you can change the logic above to

        if not hasattr(member, '_ref:  '):

It is inconvenient if API user has to create fields with default values without knowing which fields are referenced.

**Comment by hosunghwang** [comment]
I am currently blocked by this issue because dhcp member assignment requires calling restart_all_services().

**Comment by bondar-pavel** [comment]
so you need to use ib_objects.Member for restart_all_services, not AnyMember instance

**Comment by hosunghwang** [comment]
I changed it to Member as the following but still does not work.

ValueError: ValueErr...ative.',)

for member in self.ib_cxt.mapping.dhcp_members:
    ib_member = ib_objects.Member(self.ib_cxt.connector,
                                  host_name=member.member_name)
    self.ib_cxt.ibom.restart_all_services(ib_member)

**Comment by bondar-pavel** [comment]
Need some more info about the error

**Comment by bondar-pavel** [comment]
Using Member worked fine.
Observed error came from Host Record creation,
and was hidden by retry mechanizm:

```

2015-12-18 05:15:50.078 ERROR oslo_messaging.rpc.dispatcher [req-8b46f9b0-4206-45b1-a810-6481928cde31 None None] Exception during message handling: Cannot create 'record:host' object(s): { "Error": "AdmConDataError: None (IBDataConflictError: IB.Data.Conflict:The action is not allowed. A parent was not found.)",
 "code": "Client.Ibap.Data.Conflict",
 "text": "The action is not allowed. A parent was not found."
} [code 400]
