### ISSUE TITLE
Deleting DNS records that are associated with a fixed address

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#46]
According to API doc, “ipv4address” search cannot be used by cloud api because this object belongs to Host Record creation.

> “ipv4address” object has restriction “The object cannot be managed on Cloud Platform members”

That is why host record worked but not fixedaddress.

Here is the API test:

curl -k1 -u cloud:cloud -H "content-type:application/json" -w "\nThe Response Code:%{http_code}\n" https://10.40.240.101/wapi/v2.3/ipv4address?ip_address=99.90.93.10
{ "Error": "AdmConProtoError: Operation read not allowed for ipv4address on Cloud Platform member in this version",
  "code": "Client.Ibap.Proto",
  "text": "Operation read not allowed for ipv4address on Cloud Platform member in this version"
}
The Response Code:400

But searching with fixedaddress works:

curl -k1 -u cloud:cloud -H "content-type:application/json" -w "\nThe Response Code:%{http_code}\n" https://10.40.240.101/wapi/v2.3/fixedaddress?ipv4addr=99.90.93.10
[
    {
        "_ref": "fixedaddress/ZG5zLmZpeGVkX2FkZHJlc3MkOTkuOTAuOTMuMTAuMi4u:99.90.93.10/cloud_view",
        "ipv4addr": "99.90.93.10",
        "network_view": "cloud_view"
    }
]
The Response Code:200

So how come we did not see this issue before?
My guess is that NIOS had this bug and recently fixed the issue so permission is checked as mentioned in the document. However we saw that NIOS did not check superuser permission either.
We allowed the superuser on cloud api user but the API still failed. 

Anyway how can we resolve this issue now?

object_manager.delete_all_associated_objects() calls get_all_associated_objects().
This method does search using IPAddress.

obj.IPAddress.search(...)

If IP address is a fixed address, this will fail.
A funny thing is that delete_all_associated_objects() is only called from FixedAddressIPAllocator.

We probably need to make change in the interface from delete_all_associated_objects to
delete_associated_dns_records() and handle for DNS records associated the fixed address.

Also get_all_associated_objects is used by only delete_all_associated_objects.
So we need to change this method name to get_associated_dns_records.

Then how do we get DNS records from get_associated_dns_records?

Since we are not using admin credentails, we cannot use ip4addr and get dns records in one WAPI call. So we may have to do the following.

wapi/v2.3/record:a?ipv4addr=99.90.93.10
wapi/v2.3/record:aaaa?ipv6addr=2001::1    <= if ipv6 is used
wapi/v2.3/record:ptr?ipv4addr=99.90.93.10
wapi/v2.3/record:txt?ipv4addr=99.90.93.10
. . .
whateever record types defined in "dns_record_removable_types" to remove.

**Comment by bondar-pavel** [comment]
So the solution is to replace obj.IPAddress.search(...) with search by ipv4addr field in particular objects that are listed in dns_record_removable_types.
Sounds workable, will try to implement this way

**Comment by bondar-pavel** [comment]
As usual I met some issues on this way.
For 'record:a', 'record:aaaa', 'record:ptr' everything works fine and can be covered with unbind_name_from_record_a.
But 'record:txt' and 'record:cname' do not have ip fields, so it complicates process of searching them. So need to implement method similar to get_object_refs_associated_with_a_record in [1] to search 'record:cname' and 'record:txt' based on  'record:a' info.

[1] https://github.com/infobloxopen/infoblox-client/blob/f46393273619a215dc1547a703bf9e2ab91b5bf1/infoblox_client/object_manager.py#L395
