### ISSUE TITLE
Add 'record:txt' nios type into objects

### ISSUE THREAD

**Issue by bondar-pavel** [infobloxopen/infoblox-client#52]
Currently there is no objects corresponding to NIOS types 'record:cname' and 'record:txt'.
Need to add them into objects.py

**Comment by maxadamo** [comment]
There is CNAME. Maybe it was added after you wrote this issue. 
TXT is really missing :(

**Comment by bondar-pavel** [comment]
@maxadamo yep, only 'record:txt' is left to add, will update ticket description

**Comment by nbartos** [comment]
Any chance we could get txt record support?  This ticket has been open for 4 years.

**Comment by saiprasannasastry** [comment]
Will add it, closing the issues one by one, there was a release going on, will make sure this gets closed ASAP

**Comment by johnl2323** [comment]
What is the status on implementing txt record support?

**Comment by saileshgiri** [comment]
Hi @johnl2323, we've taken this up and shall provide a fix soon.

**Comment by AvRajath** [comment]
#258 Raised a PR. Should be available once accepted.
