### ISSUE TITLE
Result set too large

### ISSUE THREAD

**Issue by moranbf** [infobloxopen/infoblox-client#62]
When executing networks = conn.get_object('network')
DEBUG:infoblox_client.connector:Error occured on object search: { "Error": "AdmConProtoError: Result set too large (> 1000)", 
  "code": "Client.Ibap.Proto", 
  "text": "Result set too large (> 1000)"

The max number can be increased with &_max_results=-500000, but not sure how to pass it tot he url creation.

**Comment by bondar-pavel** [comment]
@moranbf Thanks for reporting it!
I'll investigate it deeper, but looks like we need some mechanism to load results by chunks.

**Comment by bondar-pavel** [comment]
At this point I am thinking about adding 'max_results' option to search/search_all methods.
It would refer to '_max_results' option in WAPI:

"Maximum number of objects to be returned. If set to a negative number the appliance will return an error when the number of returned objects would exceed the setting. The default is -1000. If this is set to a positive number, the results will be truncated when necessary."

For now no paging support (WAPI '_paging' option), but I'll consider adding it in future.

**Comment by bondar-pavel** [comment]
@moranbf: Hi! prepared fix for that, now it is pull requested.
So you will be able to change default output limit by:
``` 
 networks = conn.get_object('network', max_results=5000)
```

This option was also added to object model, so you can get all networks with:
```
 networks = objects.Network.search_all(conn, max_results=5000)
```
