### ISSUE TITLE
Add 'make docs' to Travis CI

### ISSUE THREAD

**Issue by bondar-pavel** [infobloxopen/infoblox-client#74]
Currently 'make docs' executed only manually (and rearely).
Now it reports quite a lot of errors/warnings, so need to automate process of cheking and building documentation.

**Comment by sarya-infoblox** [comment]
Hi @bondar-pavel, Are you still using make docs manually, and can you share the logs/error messages.

**Comment by bondar-pavel** [comment]
I have not worked on this repo for ~5 years, so I think this ticket is not relevant any more
