### ISSUE TITLE
Introduce push/pull(fetch) concept for infoblox-client objects.

### ISSUE THREAD

**Issue by bondar-pavel** [infobloxopen/infoblox-client#88]
Currently two way mechanism for exanging data between infoblox-client object instances and nios objects exists:
- fetch - data stream from nios to local object, reference can be present in object, or object can be searched by search fields in opposite case;
- update - data stream from local object to nios, send fields updates to remote object, requires to have reference set in local object and object on nios side should already exists;

And I propose to extend this concept to push - pull, where having reference and object on nios side is not  required to data stream from local object to nios:
- pull - data stream from nios to local object, it would be just an allias for 'fetch', since it already allows to get objects with or without reference;
- push - this one will do what 'update' does if reference is set, but if reference is not set, then it would try to create object on remote. It would be almost analog of current 'create' class method but for instance.

So next code would be possible:

```
network = object.Network(connector, network='192.168.1.0', networkview='default')
# wapi call for create/update fields on nios side are done in push method
network.push()
```

**Comment by hosunghwang** [comment]
fetch and pull look the same.
I don't see the difference.

update and push have a difference but it can be merged into just one.
if a reference is set, use that reference to update; if a reference does not exist, then create a new NIOS object.

Rather than introducing a similar method, it would be better to extend 'update' to handle both cases or have a 'create' method clearly in the intent of creating a NIOS object.

**Comment by sarya-infoblox** [comment]
Hi @bondar-pavel are you still active for this issue request?

**Comment by bondar-pavel** [comment]
I think it is ok to keep this one closed.
Current API is actually sufficient, so adding pull/push methods would be just a syntax sugar.
And it was not implemented in 6 years, so probably not worth doing it now.
