### ISSUE TITLE
Fields obtained using fetch() method are not converted to objects

### ISSUE THREAD

**Issue by bondar-pavel** [infobloxopen/infoblox-client#91]
If object is created using search/search_all, then fields are correctly converted to objects.
But if object info is retrieved using fetch(), then fields are shown as dicts (i.e. NIOS reply is not converted).

**Comment by sarya-infoblox** [comment]
Hi @bondar-pavel I need to check for NIOS support and I will revert back as soon as possible.

**Comment by bondar-pavel** [comment]
This one is from early days of repository existence, and I can not recall details of the original issue I had, so I think it's probably resolved by now.
I think all tickets created by me in 2016, can be closed now.
